### ISSUE TITLE
unexpected HTTP request error

### ISSUE THREAD

**Issue by antonysimstonlivera** [valiafetisov/vlc-simple-player#1]
Hello!
Intend to open vlc player from a file from nginx server. And it is working. 
Wish to use statuschange event listener, but it is throwing an error:
```
unexpected HTTP request error
SyntaxError: Unexpected token < in JSON at position 0
```

Code snippet which is being used is:
```js
let player = new VLC('http://localhost:8080/prv/01.mp4', {arguments: ['--fullscreen', '--no-video-title']});
player.on('statuschange', (error, status) => {
    if (error) return console.error(error)
    if (status.state == 'stopped') {
    }
});
```

And would like to add another files to playlist from server too.

```js
player.request('/requests/status.json?command=in_enqueue&input=http://localhost:8080/prv/02.mp4', () => {})
```

Please help.

Thanks.

**Comment by valiafetisov** [comment]
Hey @antonysimstonlivera, can you please tell me:
1. Which version of the VLC are you using
2. Which platform you're in

The below code works for me and I am able to add a second video to the playlist
```js
const VLC = require('vlc-simple-player')

const VIDEO_1 = 'http://clips.vorwaerts-gmbh.de/VfE_html5.mp4'
const VIDEO_2 = 'http://techslides.com/demos/sample-videos/small.mp4'

let player = new VLC(VIDEO_1, {
  arguments: ['--fullscreen', '--no-video-title']
});

player.on('statuschange', (error, status) => {
  if (error) return console.error(error)
});

setTimeout(() => {
  player.request('/requests/status.json?command=in_enqueue&input=' + VIDEO_2, console.log)
}, 5000)
```

**Comment by antonysimstonlivera** [comment]
Hello!
Using VLC media player 3.0.8 Vetinari in Ubuntu 18_0. 

Thanks.

**Comment by valiafetisov** [comment]
Did you tried the code above?

Can you also try accessing VLC http API manually?
1. Starting vlc with
   ```
   /path/to/vlc --extraintf http --http-password password --http-port 8080 http://clips.vorwaerts-gmbh.de/VfE_html5.mp4
   ```
2. Opening [http://:password@localhost:8080/requests/status.json](http://:password@localhost:8080/requests/status.json) in your browser? (you may need to replace `localhost` with ip address if you run it on a different machine)

3. Post here what would you get/see

**Comment by antonysimstonlivera** [comment]
Hello!
I had tried. 
Surprisingly, request error disappeared after changing port number and rebooting system. 

Thanks.
